run-name: Build presentation by @${{ github.actor }}
concurrency: build-${{ github.sha }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy images assets
        run: mkdir build && cp -R images build/images
      - name: Build presentation
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I ./ -o ./build/ --allow-local-files --pptx
        env:
          MARP_USER: root:root
      - name: Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: ppt
          folder: ./build/